POST  http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "Koodaus Blogi",
    "author": "Oppilas",
    "url": "https://www.example.com",
    "likes": 0,
    "userId": "66229ce70b8f2792195d24d6"
}